# Configuration for training RBM on MNIST digit 6 (matching original notebook)

model:
  n_visible: 121  # 11x11 downsampled images
  n_hidden: 64
  model_type: rbm

training:
  epochs: 20
  learning_rate: 0.002
  batch_size: 2
  batch_limit: 11  # Limit to ~10 batches per epoch for faster experimentation
  optimizer: sgd
  checkpoint_every: 5
  checkpoint_path: pm_rbm_digit6_checkpoint.pth

data:
  dataset: mnist
  digit_filter: 6  # Train only on digit 6
  image_size: [11, 11]  # Downsample to 11x11 (121 pixels)
  data_root: ./data
  train_split: true
  download: true

solver:
  name: gurobi
  time_limit: 60.0
  suppress_output: true

inference:
  gibbs_steps: 500
  num_generated_samples: 10
  reconstruction_samples: 5

logging:
  log_file: training_digit6.log
  save_plots: true
  plot_every: 5
  figures_dir: ./figures